In [3]:
import numpy as np
from scipy import stats

In [19]:
observed = np.array([
    [40, 30, 30],   # Under 18
    [70, 20, 10],   # 18-35
    [30, 40, 30]    # 36+
])

In [21]:
row_total = observed.sum(axis=1).reshape(-1,1)
cl_total = observed.sum(axis=0).reshape(1,-1)

In [23]:
grand_total = observed.sum()

In [25]:
grand_total

300

In [32]:
expected = (row_total @ cl_total) / grand_total

In [34]:
expected

array([[46.66666667, 30.        , 23.33333333],
       [46.66666667, 30.        , 23.33333333],
       [46.66666667, 30.        , 23.33333333]])

In [36]:
chi_stats = (((observed - expected)**2)/expected).sum()

In [38]:
chi_stats

36.666666666666664

In [40]:
df = 2

In [44]:
p_value = 1 - stats.chi2.cdf(chi_stats, df)

In [46]:
p_value

1.0912757364422987e-08

In [48]:
alpha = 0.05

In [52]:
if p_value < alpha:
    print ("rejecting the null hypothesis")

rejecting the null hypothesis


In [54]:
p_value < alpha

True

In [61]:
import pandas as pd

In [72]:
data = {'Gender':['Male','Female'],'Afternoon':[30,20],'evening':[40,10]}

In [76]:
df = pd.DataFrame(data)

In [78]:
df

Gender  Afternoon  evening
0    Male         30       40
1  Female         20       10

In [80]:
# calculate expected count

In [82]:
from scipy import stats

In [84]:
p_value = 1 - stats.chi2.cdf(4.762 , df=1)

In [86]:
p_value

0.029094721898629827

In [89]:
observed = np.array([
    [30,40],
    [20,10]
])    

In [95]:
chi_2stat, p_value, dof, expected = stats.chi2_contingency(observed)

In [99]:
print(chi_2stat, p_value, dof, expected)

3.857142857142857 0.04953461343562649 1 [[35. 35.]
 [15. 15.]]


In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [3]:
data = {'Athletes':['Endurance Athletes','Strength Athletes','Mixed Athletes', 'Total'],
        'Gatorade':[25,20,10,55],
        'Powerade':[30,15,5,50],
        'Red Bull':[15,25,5,45],
        'Total':[70,60,20,150]}

In [5]:
df = pd.DataFrame(data)

In [7]:
df

Athletes  Gatorade  Powerade  Red Bull  Total
0  Endurance Athletes        25        30        15     70
1   Strength Athletes        20        15        25     60
2      Mixed Athletes        10         5         5     20
3               Total        55        50        45    150

In [11]:
dt = np.array([
    [25,30,15],
    [20,15,25],
    [10,5,5]
])

In [13]:
chi2, p_value, dof, expected = stats.chi2_contingency(dt)

In [15]:
print(chi2, p_value, dof, expected)

9.343434343434344 0.053065660880671106 4 [[25.66666667 23.33333333 21.        ]
 [22.         20.         18.        ]
 [ 7.33333333  6.66666667  6.        ]]


In [17]:
print("Chi-square statistic:", chi2)
print("p-value:", p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-square statistic: 9.343434343434344
p-value: 0.053065660880671106
Degrees of freedom: 4
Expected frequencies:
 [[25.66666667 23.33333333 21.        ]
 [22.         20.         18.        ]
 [ 7.33333333  6.66666667  6.        ]]


In [19]:
data = [[8, 12, 10],
        [6, 10, 4],
        [2, 5, 3]]

In [21]:
chi2, p_value, dof, expected = stats.chi2_contingency(data)

In [25]:
print("Chi-Square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("p-value:", p_value)
print("Expected Frequencies:\n", expected)

Chi-Square Statistic: 1.3480392156862746
Degrees of Freedom: 4
p-value: 0.8531738666354731
Expected Frequencies:
 [[ 8.         13.5         8.5       ]
 [ 5.33333333  9.          5.66666667]
 [ 2.66666667  4.5         2.83333333]]


In [27]:
observed = [28, 42, 18, 12]
expected = [0.30*100, 0.40*100, 0.20*100, 0.10*100]

In [33]:
chi_2stats, p_value = stats.chisquare(f_obs=observed, f_exp=expected)

In [35]:
print(chi_2stats, p_value)

0.8333333333333334 0.8414786391315308


In [39]:
observed = np.array([
    [10, 15, 5],   # 18–25
    [12, 10, 8],   # 26–35
    [8, 5, 17]     # 36–45
])

In [41]:
chi2_stats, p_value, dof, expected = stats.chi2_contingency(observed)

In [45]:
print("Chi-Square Statistic:", chi2_stats)
print("p-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

Chi-Square Statistic: 13.6
p-value: 0.008687446153189466
Degrees of Freedom: 4
Expected Frequencies:
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [47]:
observed = np.array([
    [25, 20, 15],  # Male
    [10, 25, 25]   # Female
])

In [49]:
chi2, p_value, dof, expected = stats.chi2_contingency(observed)

In [51]:
print("Chi-Square Statistic:", chi2)
print("p-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

Chi-Square Statistic: 9.484126984126984
p-value: 0.00872063265020923
Degrees of Freedom: 2
Expected Frequencies:
 [[17.5 22.5 20. ]
 [17.5 22.5 20. ]]


In [53]:
p_value < 0.05

True

In [55]:
observed = np.array([
    [15, 10, 5],   # Under 25
    [10, 15, 5],   # 25–40
    [5, 10, 15]    # Over 40
])

In [57]:
chi2_stat, p_value, dof, expected = stats.chi2_contingency(observed)

In [61]:
print("Chi-Square Statistic:", chi2)
print("p-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

Chi-Square Statistic: 9.484126984126984
p-value: 0.006045682394351344
Degrees of Freedom: 4
Expected Frequencies:
 [[10.         11.66666667  8.33333333]
 [10.         11.66666667  8.33333333]
 [10.         11.66666667  8.33333333]]
